config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :topics do
    resources :bookmarks
  end

  resources :bookmarks, except: [:index] do
  resources :likes, only: [:index, :create, :destroy]
  end

  resources :users, only: [:index, :show]

  post :incoming, to: 'incoming#create'

  get 'welcome/contact'

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def index
  @topics = Topic.all
end

def show
  @topic = Topic.find(params[:id])
end

def new
  @topic = Topic.new
end

def create
  @topic = Topic.new(topic_params)

  if @topic.save
    flash[:notice] = "Topic was saved successfully."
    redirect_to @topic
  else
    flash[:alert] = "There was an error saving the topic. Please try again."
    render :new
  end
end

def edit
  @topic = Topic.find(params[:id])
end

def update
  @topic = Topic.find(params[:id])

  @topic.assign_attributes(topic_params)

  if @topic.save
    flash[:notice] = "Topic was updated"
    redirect_to @topic
  else
    flash[:alert] = "Error saving topic. Please try again."
    render :edit
  end
end

def destroy
  @topic = Topic.find(params[:id])

  if @topic.destroy
    flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
    redirect_to topics_path
  else
    flash[:alert] = "There was an error deleting the topic."
    render :show
  end
end

private

def topic_params
  params.require(:topic).permit(:title, :user)
end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>All Topics <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %></h1>

<div class="row">
  <div class="col-md-8">
    <% @topics.each do |topic| %>
        <h4 class="media-heading">
          <%= link_to topic.title, topic %>
        </h4>

      <div class="row">
        <% topic.bookmarks.each do |bookmark| %>
        <div class="col-sm-3">
          <div class="well">
            <p><%= bookmark.url %></p>
          </div>
        </div>
      <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @topic do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Please Enter Topic title" %>
      </div>

      <div class="form-group">
        <%= f.submit "save", class: 'btn btn-success' %>
      </div>
    <% end %>
     <%= link_to "Back", topics_path, class: 'btn btn-primary' %>
  </div>
</div>

app/views/topics/show.html.erb
<h1> <%= @topic.title %>
  <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
  <%= link_to "Add Bookmark", new_topic_bookmark_path(@topic), class: 'btn btn-success' %>
</h1>

<%= render partial: 'bookmarks/list', locals: { topic: @topic } %>